spring.application.name=WaterQualityMonitoring

# Database Connection
# Check karein ki MySQL mein 'water_quality_db' naam ka database bana hua hai
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/water_quality_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Mysql@12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Properties
# Ek baar 'create' run karke table banne dein, phir 'update' kar dena
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# Naya dialect for Hibernate 6+ (MySQL8Dialect purana ho gaya hai)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect